### ISSUE TITLE
Flight example not working?

### ISSUE THREAD

**Issue by maxdrohde** [cscheid/quarto-dashboard-ojs-examples#2]
This example on the Quarto Dashboard example page doesn't work for me. I tried in both Chrome and Firefox.

https://cscheid.github.io/quarto-dashboard-ojs-examples/flights.html

See below image of error. Thanks!

<img width="1783" alt="Screenshot 2024-03-19 at 18 39 14" src="https://github.com/cscheid/quarto-dashboard-ojs-examples/assets/25734232/f02ea22e-78a2-490e-b93f-fb48d43f6d20">

**Comment by cscheid** [comment]
Thanks. They've updated the APIs; I need to change this example so that we pin the versions.

**Comment by cscheid** [comment]
Fixed by [ffd8a8d](https://github.com/cscheid/quarto-dashboard-ojs-examples/commit/ffd8a8d2cabe418b1acfed6d8d7a5772cfcd1ce9)
