### ISSUE TITLE
vgplot API issue

### ISSUE THREAD

**Issue by z3tt** [cscheid/quarto-dashboard-ojs-examples#3]
Currently, the [example on linked views in the Quarto dashboard gallery using Observable](https://quarto.org/docs/dashboards/examples/#observable) is loading but not working correctly:

![image](https://github.com/quarto-dev/quarto-cli/assets/7523556/c7ae940c-f2cb-408d-95d3-c49601343e98)

The issue is likely due to a change in the `vgplot` API with this failing currently:
`const vg = await import('https://cdn.jsdelivr.net/npm/@uwdata/vgplot/+esm');`

### Note

The issue has been reported first to [quarto-cli issue #9124](https://github.com/quarto-dev/quarto-cli/issues/9124) and has been moved here as suggested by the author of the application.

**Comment by cscheid** [comment]
Yup, I already fixed that three days ago https://github.com/cscheid/quarto-dashboard-ojs-examples/commit/ffd8a8d2cabe418b1acfed6d8d7a5772cfcd1ce9
